name: Pinned repositories
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 3
